apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: utpp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: utpp
    app.kubernetes.io/part-of: byoc-app-xdno
  name: utpp
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: utpp
status:
  loadBalancer: {}
